# Generated by Django 4.0.3 on 2022-03-30 03:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repositories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mypage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recently_visit', django_mysql.models.ListCharField(models.IntegerField(), max_length=66, size=None)),
                ('recently_recommand', django_mysql.models.ListCharField(models.IntegerField(), max_length=66, size=None)),
                ('repo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repositories.repositories')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mypage',
            },
        ),
    ]
