# Generated by Django 4.0.3 on 2022-03-30 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mypage',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='mypage',
            name='repo_id',
        ),
    ]
