# Generated by Django 4.0.3 on 2022-03-30 04:28

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0003_alter_mypage_recently_recommand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypage',
            name='recently_recommand',
            field=django_mysql.models.ListCharField(models.IntegerField(), default=[], max_length=240, size=None),
        ),
        migrations.AlterField(
            model_name='mypage',
            name='recently_visit',
            field=django_mysql.models.ListCharField(models.IntegerField(), default=[], max_length=240, size=None),
        ),
    ]
