# Generated by Django 4.0.3 on 2022-03-28 16:06

import django_mysql.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Repositories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.CharField(max_length=30)),
                ("repo_id", models.IntegerField()),
                ("repo_name", models.CharField(max_length=255)),
                ("full_name", models.CharField(max_length=255)),
                (
                    "description",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                ("created", models.CharField(max_length=255)),
                ("language", models.CharField(max_length=255, null=True)),
                ("stars", models.IntegerField()),
                ("forks", models.IntegerField()),
                (
                    "topics",
                    django_mysql.models.ListCharField(models.CharField(max_length=255), max_length=66, size=None),
                ),
            ],
            options={
                "db_table": "repositories",
            },
        ),
    ]
