# Generated by Django 4.0.3 on 2022-03-30 03:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='last_visit',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='visit_count',
            field=models.IntegerField(default=0),
        ),
    ]
