# Generated by Django 4.0.3 on 2022-03-30 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_usermodel_last_visit_usermodel_visit_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="last_visit",
            field=models.DateField(auto_now=True),
        ),
    ]
