# Generated by Django 4.0.3 on 2022-03-30 03:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_usermodel_last_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='last_visit',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
